### ISSUE TITLE
'data_path' is attached to the end of resource

### ISSUE THREAD

**Issue by cxplonka** [timvink/mkdocs-charts-plugin#13]
Hi, 
thanks for you nice stuff. I currently have a problem when i want to use the option 'data_path', this is attached to the end in my project, see here:
![image](https://user-images.githubusercontent.com/13945224/226620961-186d8d50-ffb4-4339-b094-35b3c9c03a40.png)

Here is the project with sources https://cxplonka.github.io/obsidian-sandbox-mkdocs/Vega/Vega-lite%20plugin/

Hope somebody can help. 

P.S. data_path: 'docs'

Greets
Christian

**Comment by cxplonka** [comment]
Hi,
the 's' is on the next line. But this was not the problem, the problem was that i thought the 'data_path' will be insert before '/assets/data/...', but in my case 'docs' come after all. Maybe i misunderstood the meaning?

**Comment by timvink** [comment]
Still not sure I understand the exact problem. Did you manage to fix it? Are the docs unclear?
