### ISSUE TITLE
Where to set the option

### ISSUE THREAD

**Issue by chenyangkang** [timvink/mkdocs-charts-plugin#19]
Hi I'm wondering how I could set the "options" mentioned in the documentation.

Thanks a lot!

Yangkang

**Comment by timvink** [comment]
Yeah good point, docs are not very clear. I just published an improved version (https://timvink.github.io/mkdocs-charts-plugin/options/):

<img width="560" alt="image" src="https://github.com/timvink/mkdocs-charts-plugin/assets/5570380/5a135522-4fde-4c5d-b82f-659dc1b40870">
